# Stage 1: Build Stage
FROM node:18-alpine AS builder
WORKDIR /app

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code and build
COPY . .
RUN npm run build

# Stage 2: Serve Stage
# Use a very lightweight web server (Nginx) to host the static files
FROM nginx:alpine

# Copy built files from the 'builder' stage to the Nginx static directory
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]